version: 2
jobs:
  build-and-test:
    docker:
      - image: circleci/node:10.16
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: "Install dependencies"
          command: "npm install"
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: "Compile TS scripts"
          command: "npm run build"
      - run:
          name: "Run tests"
          command: npm run test
workflows:
  version: 2
  staging:
    jobs: 
    - build-and-test:
        filters:
          branches:
            only: master